config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :posts

  get 'simple_pages/contact'

  get 'simple_pages/index'

  get 'simple_pages/thank_you'

  root 'simple_pages#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user, optional: true
  validates :content, presence: true, allow_blank: false
  validates :title, presence: true, allow_blank: false

  def self.search(search_term)
    if Rails.env != "production"
      Post.where("title || content LIKE ?", "%#{search_term}%")
    else
      Post.where("title || content iLIKE ?", "%#{search_term}%")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, alert: exception.message
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:q]
      search_term = params[:q]
      @posts = Post.search(search_term)
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    if user_signed_in?
      @post = Post.new
    else
      redirect_to (new_user_session_path), alert: "You need to be logged in to post to the blog!"
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        ActionCable.server.broadcast 'post_channel', post: @post
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :timestamp)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
    @posts = Post.all.reverse
  end

  def thank_you
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :destroy]
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloggert&trade;</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

<body>
  <ul class="nav nav-tabs collapse navbar-collapse">
    <li class="nav-item">
      <a class="nav-link" href="/simple_pages/index">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/posts">Blog</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/simple_pages/contact">Contact</a>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item justify-content-end nav-link">
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
    </li>
    <% else %>
    <li class="nav-item justify-content-end nav-link">
      <%= link_to('Login', new_user_session_path)%>
    </li>
    <% end %>
  </ul>
  <div class="page-wrap" align="center">
    <center>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </center>
  </div>
  <footer class="site-footer">
    &copy; Bloggert
  </footer>
</body>
</html>

app/views/posts/_post.html.erb
<div class="page">
  <h2><%= link_to post.title, post %></h2>
  <hr>
  <p>Posted on <%= post.created_at.strftime("%m/%d/%Y") %> at <%= post.created_at.strftime("%H:%M") %></p>
  <%= post.content %>
  <br><br>
  <% if signed_in? %>
  <%= link_to 'Edit', edit_post_path(post) %> |
  <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'shared/form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="page">
  <br>
  <h1 class="header">Posts</h1>
  <%= form_with(url: posts_path, method: 'get', local: true) do |form| %>
  <%= form.text_field :q, id: 'q', value: params[:q], :placeholder => 'Enter search here...', :class => 'form-control mr-sm-2' %>
  <br>
  <%= form.submit 'Search Posts', :class => 'btn btn-primary', :type => 'submit' %>
  <% end %>
  <br>
  <p>OR</p>
  <%= link_to 'Post Something New', new_post_path, class: 'btn btn-warning'%>
</div>

<div>
  <div class="alert alert-info" style="display:none" role="alert">A new entry has been made!</div>
  <%= render @posts.reverse %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'shared/form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="page">
  <h3><%= @post.title %></h3>
  <hr>
  <p>
    <%= @post.content %>
  </p>
  <p>Posted on <%= @post.created_at.strftime("%m/%d/%Y") %> at <%= @post.created_at.strftime("%H:%M") %></p>

  <% if signed_in? %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>
  <%= link_to 'Back', posts_path %>
</div>

app/views/shared/_form.html.erb
<div class="page">
<%= form_with(model: post, local: true) do |form| %>
<% if post.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

  <ul>
    <% post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<br>
<div class="field">
  <%= form.text_field :title, placeholder: "Title", id: :post_title, class: "form-control" %>
</div>
<br>
<div class="field">
  <%= form.text_area :content, placeholder: "What's on your mind?", rows: 4, id: :post_content, class: "form-control" %>
</div>
<br>
<div class="actions">
  <%= form.submit "Submit Post", class: "btn btn-primary" %>
</div>
<% end %>
</div>

app/views/simple_pages/contact.html.erb
<br>
<div class="page">
  <h1 class="header">Contact Me</h1>

  <p>Have any questions or feel like reaching out to me?  Fill out the form below and I'll get back to you as soon as I can!</p>


  <% if notice %>
  <%= flash[:notice] %>
  <% end %>

  <%= form_with(url:"/simple_pages/thank_you", method: "get", local: true) do |form| %>
  <div>
    <div class="form-group">
      <%= form.text_field :name, class: "form-control", placeholder: "Enter Name" %>
    </div>
    <br>
    <div class="form-group">
      <%= form.text_field :email, class: "form-control", placeholder: "Enter Email" %>
    </div>
    <br>
    <div class="form-group">
      <%= form.text_area :message, class: "form-control", placeholder: "Enter Message", rows: 5 %>
    </div>
    <br>
  </div>
  <%= form.submit "Send", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/simple_pages/index.html.erb
<h1 id="blog-title" style="font-size: 6em;">Bloggert</h1>&trade;
<hr>
<h1 class="header">Newest Posts</h1>
<div class="alert alert-info" style="display:none" role="alert">A new entry has been made!</div>
<%= render @posts %>

app/views/simple_pages/thank_you.html.erb
<br>
<h3>Thanks for the feedback!  I've received your message and will get back to you as soon as possible!</h3>
<a href="/simple_pages/index">Back to Home</a>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>